- role: Technical Program Committee
  organization: USENIX Conference on File and Storage Technologies
  period: 2017, 2019, 2020, 2024, 2026
  
- role: Technical Program Committee
  organization: Non-Volatile Memories Workshop
  period: 2022

- role: Technical Program Committee
  organization: IEEE/ACM International Symposium on Cluster, Cloud and Grid Computing
  period: 2021

- role: Organizing Committee
  organization: Operating System Support for Next Generation Large Scale NVRAM
  period: 2017 -- 2023

- role: Publication Chair
  organization: Non-Volatile Memory Systems and Applications Symposium
  period: 2024

- role: Publication Chair
  organization: ACM SIGOPS Asia-Pacific Workshop on Systems
  period: 2023

- role: Publicity Chair
  organization: IEEE Non-Volatile Memory Systems and Applications Symposium
  period: 2020

- role: Editorial Member
  organization: The Journal of Systems Research
  period: 2020 -- 2021

- role: Editorial Member
  organization: Communications of the KIISE
  period: 2021

- role: Editorial Member
  organization: IEMEK Journal of Embedded Systems and Applications
  period: 2018 -- 2020

- role: Technical Referee
  organization: IEEE Transactions on Computers

- role: Technical Referee
  organization: IEEE Transactions on Very Large Scale Integration (VLSI) Systems

- role: Technical Referee
  organization: IEEE Transactions on Multi-Scale Computing
  
- role: Technical Referee
  organization: IEEE Transactions on Parallel and Distributed Systems

- role: Technical Referee
  organization: IEEE Computer Architecture Letters
  
- role: Technical Referee
  organization: IEEE Journal of the Electron Devices Society

- role: Technical Referee
  organization: ACM Transactions on Storage
